# Generated by Django 4.2.3 on 2023-08-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0003_blog_subheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
    ]
